#!/bin/bash
function testbuild {
    "$@"
    local status=$?
    if [ $status -ne 0 ]; then
        echo "error with $1"
        exit 1
    fi
    return $status
}

export NDK_MODULE_PATH=$(pwd)/../../
echo ----------------------------------------------------------------------------------------
echo Build lib
echo ----------------------------------------------------------------------------------------
testbuild ndk-build -j 8 NDK_DEBUG=1


echo ----------------------------------------------------------------------------------------
echo make resource files
echo ----------------------------------------------------------------------------------------
if test -a assets; then 
  echo "assets folder already exists"
else
  echo "create assets folder (symbolic link to resources)"
  ln -s resources assets
fi

../../tools/make_rc.py resources resource.rc resources/resource.android

echo ----------------------------------------------------------------------------------------
echo Build app
echo ----------------------------------------------------------------------------------------
ant debug

echo ----------------------------------------------------------------------------------------
echo Uninstall old app
echo ----------------------------------------------------------------------------------------
$ANDROID_HOME/platform-tools/adb uninstall com.libnui.audioengine

echo ----------------------------------------------------------------------------------------
echo Install new app
echo ----------------------------------------------------------------------------------------
$ANDROID_HOME/platform-tools/adb install bin/NativeActivity-debug.apk

echo ----------------------------------------------------------------------------------------
echo Build OK
echo ----------------------------------------------------------------------------------------
