#!/bin/bash
export NDK_MODULE_PATH=$(pwd)/../../
export NDK_PATH=$(pwd)/../../../ndk
export SDK_PATH=$(pwd)/../../../android-sdk/sdk
echo ----------------------------------------------------------------------------------------
echo Clean lib
echo ----------------------------------------------------------------------------------------
ndk-build clean 

